spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kraken?useSSL=false
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update